### ISSUE TITLE
Eshost crashing

### ISSUE THREAD

**Issue by avdg** [bterlson/eshost#9]
While testing https://github.com/bterlson/test262-harness it seems that there was a crash occuring while running following test:

https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.1_T1.js

Error log (removed base path and cut it off to install path as it was irrelevant):

```
TypeError: Cannot read property '1' of null
    at Object.parse (test262-harness\node_modules\e                                                                                                                                                       shost\lib\parseError.js:20:16)
    at NodeAgent.parseError (test262-harness\node_m                                                                                                                                                       odules\eshost\lib\ConsoleAgent.js:81:24)
    at NodeAgent.<anonymous> (test262-harness\node_                                                                                                                                                       modules\eshost\lib\ConsoleAgent.js:48:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

This might be caused due to https://github.com/bterlson/eshost/blob/6877be234b07ee3804e32dd5bd834a690a9b4a02/lib/parseError.js#L17 returning no result.

**Comment by avdg** [comment]
Using node 6.4.0 as runner.

**Comment by avdg** [comment]
Apparently the error parser can't get the error property with the current regexp from

```
 undefined:1
'
^

SyntaxError: Unexpected token ILLEGAL
    at evalmachine.<anonymous>:116:5
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> (Temp\116727-15756-1lkq1b0.2pllv50zfr.js:4:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

while attempting to parse https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.1_T1.js

**Comment by avdg** [comment]
formatted input:

```js
"undefined:1\r\n'\r\n^\r\n\r\nSyntaxError: Unexpected token ILLEGAL\r\n    at evalmachine.<anonymous>:116:5\r\n    at ContextifyScript.Script.runInThisContext (vm.js:25:33)\r\n    at Object.exports.runInThisContext (vm.js:77:17)\r\n    at Object.<anonymous> (C:\\Users\\Anthony\\AppData\\Local\\Temp\\116728-15500-6ifrpj.ipsvbcsor.js:4:10)\r\n    at Module._compile (module.js:556:32)\r\n    at Object.Module._extensions..js (module.js:565:10)\r\n    at Module.load (module.js:473:32)\r\n    at tryModuleLoad (module.js:432:12)\r\n    at Function.Module._load (module.js:424:3)\r\n    at Module.runMain (module.js:590:10)\r\n"
```

**Comment by avdg** [comment]
I wonder if the part before `:` should always contain Error (like in SyntaxError, RangeError, TypeError, etc...)

**Comment by bterlson** [comment]
It could be a custom error (eg. throw new Test262Error()). I'll investigate this more tomorrow!

**Comment by bterlson** [comment]
Turns out Node reports syntax errors from eval in a different format. eshost 3.2.0 addresses this issue, and test262-harness 2.2.0 requires eshost ^3.2.0.

Thanks for the report!!
